default: &default
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  #database: kaymodev
  database: helpy_production_bk2
  port: 5432
  host: localhost
  user: kaymo

test:
  <<: *default
  database: kaymotest
  user: kaymo


